{{- include "ledger-lens-rag-chart.validateSecrets" . -}}
{{- if not .Values.secretEnv.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ledger-lens-rag-chart.secretName" . }}
  labels:
    {{- include "ledger-lens-rag-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range .Values.secretEnv.keys }}
  {{ . }}: {{ (get $.Values.secretEnv.values .) | default "" | quote }}
  {{- end }}
{{- end }}